/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `all_languages` (
  `iso6392_code` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iso6391_code` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `english_name` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
  `native_name` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- 485 rows (aprox)
/*!40000 ALTER TABLE `all_languages` DISABLE KEYS */;
INSERT INTO `all_languages` (`iso6392_code`, `iso6391_code`, `english_name`, `native_name`) VALUES
	('aar', 'aa', 'Afar', 'Qafara'),
	('abk', 'ab', 'Abkhazian', 'Аҧсуа'),
	('ace', '', 'Acehnese, Achinese', 'Bahsa Acèh'),
	('ach', '', 'Acoli', ''),
	('ada', '', 'Adangme', 'adangbɛ'),
	('ady', '', 'Adyghe, Adygei', 'адыгэбзэ, адыгабзэ'),
	('afa', '', 'Afroasiatic languages', ''),
	('afh', '', 'Afrihili', ''),
	('afr', 'af', 'Afrikaans', 'Afrikaans'),
	('ain', '', 'Ainu (Japan)', 'アイヌ イタㇰ(イタッㇰ) or ainu itak'),
	('aka', 'ak', 'Akan', ''),
	('akk', '', 'Akkadian', 'akkadû, lišānum akkadītum'),
	('alb/sqi', 'sq', 'Albanian', 'Shqip'),
	('ale', '', 'Aleut', ''),
	('alg', '', 'Algonquian languages', ''),
	('alt', '', 'Southern Altai', 'алтай тили'),
	('amh', 'am', 'Amharic', 'አማርኛ'),
	('ang', '', 'Old English (ca. 450–1100)', 'Englisc'),
	('anp', '', 'Angika', ''),
	('apa', '', 'Apache languages', ''),
	('ara', 'ar', 'Arabic', 'العربية'),
	('arc', '', 'Official Aramaic, Imperial Aramaic (700–300 BC)', 'ܐܪܡܝܐ'),
	('arg', 'an', 'Aragonese', 'Aragonés'),
	('arm/hye', 'hy', 'Armenian', 'Հայերեն լեզու'),
	('arn', '', 'Mapudungun, Mapuche', 'mapudungun, mapuchedungun'),
	('arp', '', 'Arapaho', 'Hinóno\'eitíít'),
	('art', '', 'Artificial languages', ''),
	('arw', '', 'Arawak', ''),
	('asm', 'as', 'Assamese', 'অসমীয়া'),
	('ast', '', 'Asturian, Bable, Leonese, Asturleonese', 'asturianu, Bable, Llionés, Asturllionés'),
	('ath', '', 'Athabaskan languages', ''),
	('aus', '', 'Australian languages', ''),
	('ava', 'av', 'Avaric', 'авар мацӀ, магӀарул мацӀ'),
	('ave', 'ae', 'Avestan', 'avesta'),
	('awa', '', 'Awadhi', 'अवधी'),
	('aym', 'ay', 'Aymara', 'aymar aru'),
	('aze', 'az', 'Azerbaijani', 'Azərbaycanca'),
	('bad', '', 'Banda languages', ''),
	('bai', '', 'Bamileke languages', ''),
	('bak', 'ba', 'Bashkir', 'башҡорт теле'),
	('bal', '', 'Baluchi', 'بلوچی'),
	('bam', 'bm', 'Bambara', 'bamanankan'),
	('ban', '', 'Balinese', 'Basa Bali'),
	('baq/eus', 'eu', 'Basque', 'euskara'),
	('bas', '', 'Basa', 'ɓasaá'),
	('bat', '', 'Baltic languages', ''),
	('bej', '', 'Beja, Bedawiyet', 'بداوية'),
	('bel', 'be', 'Belarusian', 'Беларуская мова'),
	('bem', '', 'Bemba', 'ichiBemba'),
	('ben', 'bn', 'Bengali', 'বাংলা'),
	('ber', '', 'Berber languages', ''),
	('bho', '', 'Bhojpuri', 'भोजपुरी'),
	('bih', 'bh', 'Bihari languages', ''),
	('bik', '', 'Bikol', ''),
	('bin', '', 'Bini, Edo', 'Edo'),
	('bis', 'bi', 'Bislama', 'Bislama'),
	('bla', '', 'Siksika', 'siksiká,  ᓱᖽᐧᖿ'),
	('bnt', '', 'Bantu languages', ''),
	('bos', 'bs', 'Bosnian', 'bosanski jezik'),
	('bra', '', 'Braj', 'ब्रज भाषा'),
	('bre', 'br', 'Breton', 'brezhoneg'),
	('btk', '', 'Batak languages', 'Hata Batak'),
	('bua', '', 'Buriat', 'буряад хэлэн'),
	('bug', '', 'Buginese', 'ᨅᨔ ᨕᨘᨁᨗ'),
	('bul', 'bg', 'Bulgarian', 'български език'),
	('bur/mya', 'my', 'Burmese', 'မြန်မာစာ'),
	('byn', '', 'Blin, Bilin', 'ብሊና'),
	('cad', '', 'Caddo', 'Hasí:nay'),
	('cai', '', 'Central American Indian languages', ''),
	('car', '', 'Galibi Carib', ''),
	('cat', 'ca', 'Catalan, Valencian', 'català'),
	('cau', '', 'Caucasian languages', ''),
	('ceb', '', 'Cebuano', 'Sinugboanon'),
	('cel', '', 'Celtic languages', ''),
	('cha', 'ch', 'Chamorro', 'Chamoru'),
	('chb', '', 'Chibcha', ''),
	('che', 'ce', 'Chechen', 'нохчийн мотт'),
	('chg', '', 'Chagatai', 'جغتای'),
	('chi/zho', 'zh', 'Chinese', '中文'),
	('chk', '', 'Chuukese', ''),
	('chm', '', 'Mari (Russia)', 'марий йылме'),
	('chn', '', 'Chinook Jargon', ''),
	('cho', '', 'Choctaw', 'Chahta Anumpa'),
	('chp', '', 'Chipewyan, Dene Suline', 'Dëne Sųłiné, ᑌᓀᓲᒢᕄᓀ'),
	('chr', '', 'Cherokee', 'ᏣᎳᎩ'),
	('chu', 'cu', 'Church Slavonic, Church Slavic, Old Church Slavonic, Old Slavonic, Old Bulgarian', 'ѩзыкъ словѣньскъ'),
	('chv', 'cv', 'Chuvash', 'чӑваш чӗлхи'),
	('chy', '', 'Cheyenne', 'Tsêhést'),
	('cmc', '', 'Chamic languages', ''),
	('cop', '', 'Coptic', 'ⲙⲉⲧⲛ̀ⲣⲉⲙⲛ̀ⲭⲏⲙⲓ'),
	('cor', 'kw', 'Cornish', 'Kernewek'),
	('cos', 'co', 'Corsican', 'corsu, lingua corsa'),
	('cpe', '', 'creoles and pidgins, English-based', ''),
	('cpf', '', 'creoles and pidgins, French-based', ''),
	('cpp', '', 'creoles and pidgins, Portuguese-based', ''),
	('cre', 'cr', 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ'),
	('crh', '', 'Crimean Tatar, Crimean Turkish', 'qırımtatar tili, къырымтатар тили'),
	('crp', '', 'creoles and pidgins', ''),
	('csb', '', 'Kashubian', 'kaszëbsczi jãzëk'),
	('cus', '', 'Cushitic languages', ''),
	('cze/ces', 'cs', 'Czech', 'čeština (substantive), česky (adverb)'),
	('dak', '', 'Dakota', 'Lakhota'),
	('dan', 'da', 'Danish', 'dansk'),
	('dar', '', 'Dargwa', 'дарган мез'),
	('day', '', 'Land Dayak languages', ''),
	('del', '', 'Delaware', 'Lënape'),
	('den', '', 'Slave (Athapascan)', ''),
	('dgr', '', 'Dogrib', 'Tłįchǫ'),
	('din', '', 'Dinka', 'Thuɔŋjäŋ'),
	('div', 'dv', 'Divehi, Dhivehi, Maldivian', 'ދިވެހިބަސ'),
	('doi', '', 'Dogri', 'डोगरी'),
	('dra', '', 'Dravidian languages', ''),
	('dsb', '', 'Lower Sorbian', 'dolnoserbski'),
	('dua', '', 'Duala', ''),
	('dum', '', 'Dutch, Middle (ca. 1050–1350)', ''),
	('dut/nld', 'nl', 'Dutch, Flemish', 'Nederlands'),
	('dyu', '', 'Dyula', 'Julakan'),
	('dzo', 'dz', 'Dzongkha', 'རྫོང་ཁ'),
	('efi', '', 'Efik', ''),
	('egy', '', 'Egyptian (Ancient)', ''),
	('eka', '', 'Ekajuk', ''),
	('elx', '', 'Elamite', ''),
	('eng', 'en', 'English', 'English'),
	('enm', '', 'Middle English (1100–1500)', 'Middle English (1100–1500)'),
	('epo', 'eo', 'Esperanto', 'Esperanto'),
	('est', 'et', 'Estonian', 'eesti keel'),
	('ewe', 'ee', 'Ewe', 'Ɛʋɛgbɛ'),
	('ewo', '', 'Ewondo', ''),
	('fan', '', 'Fang', ''),
	('fao', 'fo', 'Faroese', 'føroyskt'),
	('fat', '', 'Fanti', ''),
	('fij', 'fj', 'Fijian', 'vosa Vakaviti'),
	('fil', '', 'Filipino, Pilipino', 'Wikang Filipino'),
	('fin', 'fi', 'Finnish', 'suomi, suomen kieli'),
	('fiu', '', 'Finno-Ugric languages', ''),
	('fon', '', 'Fon', 'Fɔngbe'),
	('fre/fra', 'fr', 'French', 'français, langue française'),
	('frm', '', 'Middle French (ca. 1400—1600)', ''),
	('fro', '', 'Old French (842—ca. 1400)', ''),
	('frr', '', 'Northern Frisian', ''),
	('frs', '', 'Eastern Frisian', 'Seeltersk Fräisk, Seeltersk, Fräisk'),
	('fry', 'fy', 'Western Frisian', 'frysk'),
	('ful', 'ff', 'Fulah', 'Fulfulde, Pulaar, Pular'),
	('fur', '', 'Friulian', 'furlan'),
	('gaa', '', 'Ga', 'Gã'),
	('gay', '', 'Gayo', ''),
	('gba', '', 'Gbaya', ''),
	('gem', '', 'Germanic languages', ''),
	('geo/kat', 'ka', 'Georgian', 'ქართული ენა (kartuli ena)'),
	('ger/deu', 'de', 'German', 'Deutsch'),
	('gez', '', 'Ge\'ez', 'ግዕዝ'),
	('gil', '', 'Gilbertese, Kiribati', 'taetae ni Kiribati'),
	('gla', 'gd', 'Scottish Gaelic, Gaelic', 'Gàidhlig'),
	('gle', 'ga', 'Irish', 'Gaeilge'),
	('glg', 'gl', 'Galician', 'Galego'),
	('glv', 'gv', 'Manx', 'Gaelg, Manninagh'),
	('gmh', '', 'Middle High German (ca. 1050–1500)', 'diutisk'),
	('goh', '', 'Old High German (ca. 750–1050)', 'diutisc'),
	('gon', '', 'Gondi', 'Gōndi'),
	('gor', '', 'Gorontalo', ''),
	('got', '', 'Gothic', ''),
	('grb', '', 'Grebo', ''),
	('grc', '', 'Ancient Greek (–1453)', 'Ἑλληνικά'),
	('gre/ell', 'el', 'Modern Greek (1453–)', 'Ελληνικά'),
	('grn', 'gn', 'Guarani', 'Avañe\'ẽ'),
	('gsw', '', 'Swiss German, Alemannic', 'Schwyzerdütsch, Alemannisch'),
	('guj', 'gu', 'Gujarati', 'ગુજરાતી'),
	('gwi', '', 'Gwichʼin', ''),
	('hai', '', 'Haida', 'X̲aat Kíl'),
	('hat', 'ht', 'Haitian Creole, Haitian', 'Kreyòl ayisyen'),
	('hau', 'ha', 'Hausa', 'Hausancī, هَوُسَ'),
	('haw', '', 'Hawaiian', '‘Ōlelo Hawai‘i'),
	('heb', 'he', 'Hebrew', 'עִבְרִית, עברית'),
	('her', 'hz', 'Herero', 'Otjiherero'),
	('hil', '', 'Hiligaynon', 'Ilonggo'),
	('him', '', 'Himachali languages', ''),
	('hin', 'hi', 'Hindi', 'हिन्दी'),
	('hit', '', 'Hittite', ''),
	('hmn', '', 'Hmong', 'Hmoob'),
	('hmo', 'ho', 'Hiri Motu', 'Hiri Motu'),
	('hrv', 'hr', 'Croatian', 'hrvatski jezik'),
	('hsb', '', 'Upper Sorbian', 'hornjoserbsce'),
	('hun', 'hu', 'Hungarian', 'magyar'),
	('hup', '', 'Hupa', 'Na:tinixwe Mixine:whe'),
	('iba', '', 'Iban', ''),
	('ibo', 'ig', 'Igbo', 'Igbo'),
	('ice/isl', 'is', 'Icelandic', 'íslenska'),
	('ido', 'io', 'Ido', 'Ido'),
	('iii', 'ii', 'Sichuan Yi, Nuosu', 'ꆇꉙ'),
	('ijo', '', 'Ijo languages', ''),
	('iku', 'iu', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'),
	('ile', 'ie', 'Interlingue, Occidental', 'Interlingue'),
	('ilo', '', 'Iloko', ''),
	('ina', 'ia', 'Interlingua (International Auxiliary Language Association)', 'interlingua'),
	('inc', '', 'Indic languages', ''),
	('ind', 'id', 'Indonesian', 'Bahasa Indonesia'),
	('ine', '', 'Indo-European languages', ''),
	('inh', '', 'Ingush', 'гӀалгӀай мотт'),
	('ipk', 'ik', 'Inupiaq', 'Iñupiaq, Iñupiatun'),
	('ira', '', 'Iranian languages', ''),
	('iro', '', 'Iroquoian languages', ''),
	('ita', 'it', 'Italian', 'italiano'),
	('jav', 'jv', 'Javanese', 'basa Jawa (ꦧꦱꦗꦮ)'),
	('jbo', '', 'Lojban', 'lojban'),
	('jpn', 'ja', 'Japanese', '日本語 (にほんご)'),
	('jpr', '', 'Judæo-Persian', ''),
	('jrb', '', 'Judeo-Arabic', ''),
	('kaa', '', 'Kara-Kalpak', 'қарақалпақ тили'),
	('kab', '', 'Kabyle', 'Taqbaylit'),
	('kac', '', 'Kachin, Jingpho', 'Jingpho, Marip'),
	('kal', 'kl', 'Greenlandic, Kalaallisut', 'kalaallisut, kalaallit oqaasii'),
	('kam', '', 'Kamba', ''),
	('kan', 'kn', 'Kannada', 'ಕನ್ನಡ'),
	('kar', '', 'Karen languages', ''),
	('kas', 'ks', 'Kashmiri', 'कॉशुर, کٲشُر'),
	('kau', 'kr', 'Kanuri', ''),
	('kaw', '', 'Kawi', 'Bhāṣa Kawi'),
	('kaz', 'kk', 'Kazakh', 'Қазақ тілі'),
	('kbd', '', 'Circassian', 'Адыгэбзэ'),
	('kha', '', 'Khasi', 'Khasi'),
	('khi', '', 'Khoisan languages', ''),
	('khm', 'km', 'Central Khmer', 'ភាសាខ្មែរ'),
	('kho', '', 'Khotanese, Sakan', 'Khotanese, Sakan'),
	('kik', 'ki', 'Kikuyu, Gikuyu', 'Gĩkũyũ'),
	('kin', 'rw', 'Kinyarwanda', 'Ikinyarwanda'),
	('kir', 'ky', 'Kirghiz, Kyrgyz', 'кыргыз тили'),
	('kmb', '', 'Kimbundu', ''),
	('kok', '', 'Konkani', 'कॊंकणि'),
	('kom', 'kv', 'Komi', 'коми кыв'),
	('kon', 'kg', 'Kongo', 'Kikongo'),
	('kor', 'ko', 'Korean', '한국어 (韓國語), 조선말 (朝鮮語)'),
	('kos', '', 'Kosraean', 'Kosrae'),
	('kpe', '', 'Kpelle', 'kpele'),
	('krc', '', 'Karachay-Balkar', 'къарачай-малкъар тил'),
	('krl', '', 'Karelian', 'karjalan kieli'),
	('kro', '', 'Kru languages', ''),
	('kru', '', 'Kurukh', ''),
	('kua', 'kj', 'Kuanyama, Kwanyama', ''),
	('kum', '', 'Kumyk', 'Кумык'),
	('kur', 'ku', 'Kurdish', 'Kurdî'),
	('kut', '', 'Kutenai', 'Ktunaxa'),
	('lad', '', 'Ladino', 'ג\'ודיאו-איספאנייול'),
	('lah', '', 'Lahnda', 'ਲਹਿੰਦੀ'),
	('lam', '', 'Lamba', ''),
	('lao', 'lo', 'Lao', 'ພາສາລາວ'),
	('lat', 'la', 'Latin', 'latine, lingua Latina'),
	('lav', 'lv', 'Latvian', 'latviešu valoda'),
	('lez', '', 'Lezghian', 'лезги чӀал'),
	('lim', 'li', 'Limburgish, Limburger, Limburgan', 'Limburgs'),
	('lin', 'ln', 'Lingala', 'lingala'),
	('lit', 'lt', 'Lithuanian', 'lietuvių kalba'),
	('lol', '', 'Mongo', ''),
	('loz', '', 'Lozi', 'siLozi'),
	('ltz', 'lb', 'Luxembourgish, Letzeburgesch', 'Lëtzebuergesch'),
	('lua', '', 'Luba-Lulua', 'lwaà:'),
	('lub', 'lu', 'Luba-Katanga', ''),
	('lug', 'lg', 'Luganda', 'Luganda'),
	('lui', '', 'Luiseño', ''),
	('lun', '', 'Lunda', 'chiLunda'),
	('luo', '', 'Luo (Kenya and Tanzania)', 'Dholuo'),
	('lus', '', 'Lushai', ''),
	('mac/mkd', 'mk', 'Macedonian', 'македонски јазик'),
	('mad', '', 'Madurese', ''),
	('mag', '', 'Magahi', ''),
	('mah', 'mh', 'Marshallese', 'Kajin M̧ajeļ'),
	('mai', '', 'Maithili', 'मैथिली'),
	('mak', '', 'Makasar', ''),
	('mal', 'ml', 'Malayalam', 'മലയാളം'),
	('man', '', 'Mandingo', ''),
	('mao/mri', 'mi', 'Māori', 'te reo Māori'),
	('map', '', 'Austronesian languages', ''),
	('mar', 'mr', 'Marathi', 'मराठी'),
	('mas', '', 'Maasai', 'ɔl Maa'),
	('may/msa', 'ms', 'Malay', 'bahasa Melayu, بهاس ملايو'),
	('mdf', '', 'Moksha', 'мокшень кяль'),
	('mdr', '', 'Mandar', ''),
	('men', '', 'Mende', 'Mɛnde'),
	('mga', '', 'Middle Irish (900–1200)', 'Gaoidhealg'),
	('mic', '', 'Mi\'kmaq, Micmac', 'Míkmaq, Mi\'gmaq'),
	('min', '', 'Minangkabau', 'Baso Minangkabau'),
	('mis', '', 'Uncoded languages', ''),
	('mkh', '', 'Mon-Khmer languages', ''),
	('mlg', 'mg', 'Malagasy', 'Malagasy fiteny'),
	('mlt', 'mt', 'Maltese', 'Malti'),
	('mnc', '', 'Manchu', 'ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ ᠪᡝ'),
	('mni', '', 'Manipuri', 'মৈইতৈইলোন'),
	('mno', '', 'Manobo languages', ''),
	('moh', '', 'Mohawk', 'Kanien’keha'),
	('mon', 'mn', 'Mongolian', 'монгол хэл'),
	('mos', '', 'Mossi', 'Mòoré'),
	('mul', '', 'Multiple languages', ''),
	('mun', '', 'Munda languages', ''),
	('mus', '', 'Creek', 'Maskoki, Mvskokē empunakv'),
	('mwl', '', 'Mirandese', 'Lhéngua Mirandesa'),
	('mwr', '', 'Marwari', 'मारवाड़ी'),
	('myn', '', 'Mayan languages', ''),
	('myv', '', 'Erzya', 'эрзянь кель'),
	('nah', '', 'Nahuatl', 'nāhuatl, nawatlahtolli'),
	('nai', '', 'North American Indian languages', ''),
	('nap', '', 'Neapolitan', 'napulitano'),
	('nau', 'na', 'Nauruan', 'Ekakairũ Naoero'),
	('nav', 'nv', 'Navajo, Navaho', 'Diné bizaad, Dinékʼehǰí'),
	('nbl', 'nr', 'Southern Ndebele', 'isiNdebele'),
	('nde', 'nd', 'Northern Ndebele', 'isiNdebele'),
	('ndo', 'ng', 'Ndonga', 'Owambo'),
	('nds', '', 'Low German, Low Saxon', 'Nederdüütsch, Plattdüütsch'),
	('nep', 'ne', 'Nepali', 'नेपाली'),
	('new', '', 'Nepal Bhasa, Newari', 'Nepal Bhasa'),
	('nia', '', 'Nias', ''),
	('nic', '', 'Niger-Kordofanian languages', ''),
	('niu', '', 'Niuean', 'ko e vagahau Niuē, faka-Niue'),
	('nno', 'nn', 'Norwegian Nynorsk', 'nynorsk'),
	('nob', 'nb', 'Norwegian Bokmål', 'bokmål'),
	('nog', '', 'Nogai', 'ногай тили'),
	('non', '', 'Old Norse', 'norskr'),
	('nor', 'no', 'Norwegian', 'norsk'),
	('nqo', '', 'N\'Ko', ''),
	('nso', '', 'Northern Sotho, Pedi, Sepedi', 'Sesotho sa Leboa, Sepedi'),
	('nub', '', 'Nubian languages', ''),
	('nwc', '', 'Classical Newari, Old Newari, Classical Nepal Bhasa', ''),
	('nya', 'ny', 'Chichewa, Chewa, Nyanja', 'chiCheŵa, chinyanja'),
	('nym', '', 'Nyamwezi', 'Kinyamwezi'),
	('nyn', '', 'Nyankole', ''),
	('nyo', '', 'Nyoro', 'Runyoro'),
	('nzi', '', 'Nzima', ''),
	('oci', 'oc', 'Occitan (1500–)', 'Occitan'),
	('oji', 'oj', 'Ojibwa', 'ᐊᓂᔑᓇᐯᒧᐏᐣ (Anishinaabemowin)'),
	('ori', 'or', 'Oriya', 'ଓଡ଼ିଆ'),
	('orm', 'om', 'Oromo', 'Afaan Oromoo'),
	('osa', '', 'Osage', ''),
	('oss', 'os', 'Ossetian, Ossetic', 'ирон ӕвзаг'),
	('ota', '', 'Turkish, Ottoman (1500–1928)', ''),
	('oto', '', 'Otomian languages', ''),
	('paa', '', 'Papuan languages', ''),
	('pag', '', 'Pangasinan', ''),
	('pal', '', 'Pahlavi, (Middle Persian)', ''),
	('pam', '', 'Pampanga, Kapampangan', 'Kapampangan'),
	('pan', 'pa', 'Punjabi, Panjabi', 'ਪੰਜਾਬੀ, پنجابی'),
	('pap', '', 'Papiamento', 'Papiamentu'),
	('pau', '', 'Palauan', 'tekoi ra Belau'),
	('peo', '', 'Old Persian (ca. 600–400 BC)', ''),
	('per/fas', 'fa', 'Persian', 'فارسی'),
	('phi', '', 'Philippine languages', ''),
	('phn', '', 'Phoenician', ''),
	('pli', 'pi', 'Pali', 'पालि'),
	('pol', 'pl', 'Polish', 'polski'),
	('pon', '', 'Pohnpeian', ''),
	('por', 'pt', 'Portuguese', 'português'),
	('pra', '', 'Prakrit', ''),
	('pro', '', 'Old Provençal, Old Occitan (–1500)', ''),
	('pus', 'ps', 'Pashto language, Pashto', 'پښتو'),
	('qaa-qtz', '', 'Reserved for local use', ''),
	('que', 'qu', 'Quechua', 'Runa Simi, Kichwa'),
	('raj', '', 'Rajasthani', 'राजस्थानी'),
	('rap', '', 'Rapanui', 'rapanui, pepito ote henua'),
	('rar', '', 'Rarotongan, Cook Islands Maori', ''),
	('roa', '', 'Romance languages', ''),
	('roh', 'rm', 'Romansh', 'rumantsch grischun'),
	('rom', '', 'Romany', 'rromani ćhib, Romani šib, Romanó'),
	('rum/ron', 'ro', 'Romanian', 'română'),
	('run', 'rn', 'Rundi', 'Rundi'),
	('rup', '', 'Aromanian, Arumanian, Macedo-Romanian', 'Armãneashce, Armãneashti, Limba armãneascã'),
	('rus', 'ru', 'Russian', 'русский язык'),
	('sad', '', 'Sandawe', ''),
	('sag', 'sg', 'Sango', 'yângâ tî sängö'),
	('sah', '', 'Yakut', 'Саха тыла'),
	('sai', '', 'South American Indian languages', ''),
	('sal', '', 'Salishan languages', ''),
	('sam', '', 'Samaritan Aramaic', 'ארמית, ܐܪܡܝܐ'),
	('san', 'sa', 'Sanskrit', 'संस्कृतम्'),
	('sas', '', 'Sasak', ''),
	('sat', '', 'Santali', 'संथाली'),
	('scn', '', 'Sicilian', 'Sicilianu'),
	('sco', '', 'Scots', 'Scots leid, Lallans'),
	('sel', '', 'Selkup', 'шӧльӄумыт әты'),
	('sem', '', 'Semitic languages', ''),
	('sga', '', 'Old Irish (to 900)', 'Goídelc'),
	('sgn', '', 'Sign languages', ''),
	('shn', '', 'Shan', ''),
	('sid', '', 'Sidamo', 'Sidámo \'Afó'),
	('sin', 'si', 'Sinhalese, Sinhala', 'සිංහල'),
	('sio', '', 'Siouan languages', ''),
	('sit', '', 'Sino-Tibetan languages', ''),
	('sla', '', 'Slavic languages', ''),
	('slk/slo', 'sk', 'Slovak', 'slovenčina'),
	('slv', 'sl', 'Slovenian', 'slovenščina'),
	('sma', '', 'Southern Sami', 'saemien giele'),
	('sme', 'se', 'Northern Sami', 'sámi, sámegiella'),
	('smi', '', 'Sami languages', ''),
	('smj', '', 'Lule Sami', 'sámegiella'),
	('smn', '', 'Inari Sami', 'säämegiella'),
	('smo', 'sm', 'Samoan', 'gagana fa\'a Samoa'),
	('sms', '', 'Skolt Sami', 'sääʼmǩiõll'),
	('sna', 'sn', 'Shona', 'chiShona'),
	('snd', 'sd', 'Sindhi', 'سنڌي، سندھی, सिन्धी'),
	('snk', '', 'Soninke', 'Soninkanxaane'),
	('sog', '', 'Sogdian', ''),
	('som', 'so', 'Somali', 'Soomaaliga, af Soomaali'),
	('son', '', 'Songhay languages', ''),
	('sot', 'st', 'Southern Sotho', 'Sesotho'),
	('spa', 'es', 'Spanish, Castilian', 'español, castellano'),
	('srd', 'sc', 'Sardinian', 'sardu'),
	('srn', '', 'Sranan Tongo', ''),
	('srp', 'sr', 'Serbian', 'српски језик, srpski jezik'),
	('srr', '', 'Serer', ''),
	('ssa', '', 'Nilo-Saharan languages', ''),
	('ssw', 'ss', 'Swati', 'siSwati'),
	('suk', '', 'Sukuma', ''),
	('sun', 'su', 'Sundanese', 'basa Sunda'),
	('sus', '', 'Susu', ''),
	('sux', '', 'Sumerian', 'eme-ĝir'),
	('swa', 'sw', 'Swahili', 'Kiswahili'),
	('swe', 'sv', 'Swedish', 'svenska'),
	('syc', '', 'Classical Syriac', ''),
	('syr', '', 'Syriac (Northeastern Neo-Aramaic)', 'ܣܘܪܝܝܐ'),
	('tah', 'ty', 'Tahitian', 'te reo Tahiti, te reo Māʼohi'),
	('tai', '', 'Tai languages', ''),
	('tam', 'ta', 'Tamil', 'தமிழ்'),
	('tat', 'tt', 'Tatar', 'татарча, tatarça, تاتارچا'),
	('tel', 'te', 'Telugu', 'తెలుగు'),
	('tem', '', 'Time', ''),
	('ter', '', 'Tereno', ''),
	('tet', '', 'Tetum', 'Tetun'),
	('tgk', 'tg', 'Tajik', 'тоҷикӣ, تاجیکی'),
	('tgl', 'tl', 'Tagalog', 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔'),
	('tha', 'th', 'Thai', 'ภาษาไทย'),
	('tib/bod', 'bo', 'Tibetan', 'བོད་ཡིག'),
	('tig', '', 'Tigre', 'Tigré, Khasa'),
	('tir', 'ti', 'Tigrinya', 'ትግርኛ'),
	('tiv', '', 'Tiv', ''),
	('tkl', '', 'Tokelau', 'Tokelau'),
	('tlh', '', 'Klingon, tlhIngan-Hol', 'tlhIngan Hol'),
	('tli', '', 'Tlingit', 'Lingít'),
	('tmh', '', 'Tamashek', 'Tamajeq'),
	('tog', '', 'Tonga (Nyasa)', 'chiTonga'),
	('ton', 'to', 'Tonga (Tonga Islands)', 'faka-Tonga'),
	('tpi', '', 'Tok Pisin', 'Tok Pisin'),
	('tsi', '', 'Tsimshian', ''),
	('tsn', 'tn', 'Tswana', 'Setswana'),
	('tso', 'ts', 'Tsonga', 'Xitsonga'),
	('tuk', 'tk', 'Turkmen', 'Түркмен'),
	('tum', '', 'Tumbuka', 'chiTumbuka'),
	('tup', '', 'Tupian languages', 'Nheengatu'),
	('tur', 'tr', 'Turkish', 'Türkçe'),
	('tut', '', 'Altaic languages', ''),
	('tvl', '', 'Tuvalu', '\'gana Tuvalu'),
	('twi', 'tw', 'Twi', ''),
	('tyv', '', 'Tuvinian', 'тыва дыл'),
	('udm', '', 'Udmurt', 'удмурт кыл'),
	('uga', '', 'Ugaritic', ''),
	('uig', 'ug', 'Uighur, Uyghur', 'Uyƣurqə, Uyğurçe, ئۇيغۇرچ'),
	('ukr', 'uk', 'Ukrainian', 'українська мова'),
	('umb', '', 'Umbundu', 'úmbúndú'),
	('und', '', 'Undetermined language', ''),
	('urd', 'ur', 'Urdu', 'اردو'),
	('uzb', 'uz', 'Uzbek', 'O\'zbek, Ўзбек, أۇزبېك'),
	('vai', '', 'Vai', ''),
	('ven', 've', 'Venda', 'Tshivenḓa'),
	('vie', 'vi', 'Vietnamese', 'Tiếng Việt'),
	('vol', 'vo', 'Volapük', 'Volapük'),
	('vot', '', 'Votic', 'vaďďa tšeeli'),
	('wak', '', 'Wakashan languages', ''),
	('wal', '', 'Wolaytta, Wolaitta', ''),
	('war', '', 'Waray-Waray', 'Winaray, Lineyte-Samarnon'),
	('was', '', 'Washo', ''),
	('wel/cym', 'cy', 'Welsh', 'Cymraeg'),
	('wen', '', 'Sorbian languages', ''),
	('wln', 'wa', 'Walloon', 'walon'),
	('wol', 'wo', 'Wolof', 'Wolof'),
	('xal', '', 'Kalmyk, Oirat', 'хальмг келн'),
	('xho', 'xh', 'Xhosa', 'isiXhosa'),
	('yao', '', 'Yao', 'Chiyao'),
	('yap', '', 'Yapese', ''),
	('yid', 'yi', 'Yiddish', 'ייִדיש'),
	('yor', 'yo', 'Yoruba', 'Yorùbá'),
	('ypk', '', 'Yupik languages', ''),
	('zap', '', 'Zapotec', ''),
	('zbl', '', 'Blissymbols, Blissymbolics, Bliss', ''),
	('zen', '', 'Zenaga', 'Tuḍḍungiyya'),
	('zha', 'za', 'Zhuang, Chuang', 'Saɯ cueŋƅ, Saw cuengh'),
	('znd', '', 'Zande languages', 'Pazande'),
	('zul', 'zu', 'Zulu', 'isiZulu'),
	('zun', '', 'Zuni', 'Shiwi'),
	('zxx', '', 'No linguistic content; not applicable', ''),
	('zza', '', 'Zaza, Dimili, Dimli, Kirdki, Kirmanjki, Zazaki', '');
/*!40000 ALTER TABLE `all_languages` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
